/** Default Z coordinate of the 2D playing plane (used as fallback; v2 picks per-game from scout). */
export const PLAY_Z = 0;

/** Camera distance north (positive Z) of the player. */
export const CAMERA_Z_OFFSET = 15;

/** Camera height offset above the player's feet. */
export const CAMERA_Y_OFFSET = 1;

/** Player yaw when facing east (right on screen). -90 = east in Minecraft. */
export const PLAYER_FACING_YAW = -90;

/** Default Y coordinate of the ground surface (used as fallback). */
export const LEVEL_Y = 100;

/** How many blocks below ground a fall counts as a death. */
export const FALL_DEPTH = 4;

/** Consecutive ticks the player must stay below the fall threshold before a
 *  death triggers. Gives a grace period to recover from small dips. */
export const FALL_GRACE_TICKS = 30; // 1.5s @ 20 tps

/** Max blocks per tick the fall-death threshold may descend to follow the
 *  surface under the player. Walking a ramp/dip lowers the surface gradually
 *  (well under 1 block/tick), but a crevice the player falls into drops the
 *  column surface many blocks in a single tick — we refuse to chase that, so
 *  the gap is correctly registered as a fall. */
export const MAX_SAFE_DESCENT_PER_TICK = 1;

/** How far behind the playing plane (positive Z toward camera) to clear blocks for visibility. */
export const CLEAR_Z_BEHIND = 14;

/** Height above LEVEL_Y to clear for visibility. */
export const CLEAR_HEIGHT = 25;

/** Number of extra X blocks to clear/barrier beyond level bounds. */
export const MARGIN_X = 10;

/** Height of barrier walls above LEVEL_Y. */
export const BARRIER_HEIGHT = 30;

/** Depth of barrier walls below LEVEL_Y. */
export const BARRIER_DEPTH = 4;

/** How many X-blocks ahead/behind the player to keep cleared incrementally. */
export const CLEAR_WINDOW_HALF = 30;

// ── Site Scouting  ──────────────────────────────────────────────────────

/** How many candidate sites to probe per /scriptevent tossLab:start. */
export const SCOUT_COUNT = 10;

/** Minimum horizontal distance from the player when picking candidates. */
export const SCOUT_RADIUS_MIN = 200;

/** Maximum horizontal distance from the player when picking candidates. */
export const SCOUT_RADIUS_MAX = 2000;

/** Half-width (X & Z) of the probe ticking area used for scoring. */
export const SCOUT_PROBE_HALF = 24;

/** Maximum probe ticking areas in flight at once. */
export const SCOUT_PARALLELISM = 3;

/** Sampling step (blocks) when scoring a candidate. */
export const SCOUT_SAMPLE_STEP = 2;

// ── Streaming Level Builder  ────────────────────────────────────────────

/** Width (in blocks) of one segment generated by the streaming builder. */
export const SEGMENT_WIDTH = 24;

/** Build segments at least this many blocks ahead of the player. */
export const LOOKAHEAD_BLOCKS = 80;

/** Initial number of blocks to prebuild ahead of start before the player can move. */
export const INITIAL_PREBUILD_BLOCKS = 120;

/** Don't build new segments closer than this many blocks behind the start. */
export const PRUNE_BEHIND_BLOCKS = 120;

/** Approximate spacing between puzzle segments (range, in segment counts). */
export const PUZZLE_INTERVAL_MIN = 3;
export const PUZZLE_INTERVAL_MAX = 6;

/** Print a milestone message every N blocks of forward progress made by the player. */
export const MILESTONE_INTERVAL_BLOCKS = 50;

// ── Aim & Throw ─────────────────────────────────────────────────────────────

/** Degrees per tick the aim angle changes when A/D is held. */
export const AIM_SPEED = 3;

/** Distance (blocks) from the player's head to the aim reticle. */
export const RETICLE_DISTANCE = 3;

/** Impulse magnitude applied to thrown projectiles. */
export const THROW_FORCE = 1.5;

/** Minimum ticks between throws. */
export const THROW_COOLDOWN = 10;

/** Max ticks a thrown projectile can live before it auto-converts back to an item. */
export const PROJECTILE_MAX_LIFETIME_TICKS = 400; // 20s @ 20 tps

/** Consecutive ticks of near-zero velocity that count as "at rest". */
export const PROJECTILE_REST_TICKS = 100; // 5s @ 20 tps

/** Velocity magnitude (blocks/second) below which a projectile is considered at rest. */
export const PROJECTILE_REST_VELOCITY = 0.5;

// ── Projectiles ─────────────────────────────────────────────────────────────

/**
 * The five physics-puzzle projectiles available to the player.
 * Each one demonstrates a different combination of the new entity
 * physics components (bounciness, air drag, friction, knockback rules,
 * pushable_by_entity).
 */
export interface ProjectileDef {
  /** Item id (matches behavior_pack/items/<id>.json identifier). */
  itemId: string;
  /** Entity id spawned when thrown. */
  entityId: string;
  /** Display label for the action bar. */
  label: string;
  /** Per-throw impulse multiplier (heavier objects get a stronger throw). */
  forceMultiplier: number;
}

export const PROJECTILES: ProjectileDef[] = [
  {
    itemId: "toss_lab:rubber_sphere",
    entityId: "toss_lab:rubber_sphere",
    label: "Rubber Sphere",
    forceMultiplier: 1.0,
  },
  { itemId: "toss_lab:heavy_stone", entityId: "toss_lab:heavy_stone", label: "Heavy Stone", forceMultiplier: 0.4 },
  { itemId: "toss_lab:cotton_puff", entityId: "toss_lab:cotton_puff", label: "Cotton Puff", forceMultiplier: 0.8 },
  { itemId: "toss_lab:ice_disc", entityId: "toss_lab:ice_disc", label: "Ice Disc", forceMultiplier: 0.9 },
  { itemId: "toss_lab:sticky_glob", entityId: "toss_lab:sticky_glob", label: "Sticky Glob", forceMultiplier: 1.0 },
];
